# -*- coding: utf-8 -*-
"""Suggested relevance codes for the two random samples (to be confirmed by the authors).
A = UAV is the sensing platform AND the application is ecological / environmental monitoring or protection
B = UAV is the platform, but the application is adjacent (precision agriculture, urban/geodetic survey, generic UAV tech)
C = not relevant (no aerial UAV: bee drones, other acronyms, underwater drones; or UAV with no environmental application)
"""
S100 = {
 1:('C','Virtualna stvarnost; dronske snimke samo kao izvor podataka'), 2:('A','UAV spektralno snimanje tla u studiji GHG emisija tresetišta'),
 3:('A','UAV kartiranje plastičnog onečišćenja obale'), 4:('A','Inventura hrasta, UAV + satelit, upravljanje šumama'),
 5:('A','Širina šumskih pojaseva, UAV RGB (ekološka funkcija)'), 6:('B','Precizna poljoprivreda: pamuk, navodnjavanje'),
 7:('C','„Drone“ = trut (pčele)'), 8:('A','Termalni dronovi za popis divljači'),
 9:('A','Invazivna vodena biljka, dron + duboko učenje'), 10:('B','Poljoprivredna kultura Opuntia, segmentacija'),
 11:('C','„UAS“ = urban agglomerations, nema letjelice'), 12:('B','Pregled daljinskih istraživanja štetnika usjeva; UAV kao jedan izvor'),
 13:('A','Obalne dine, UAV LiDAR i fotogrametrija'), 14:('A','Biomasa močvara UAV fotogrametrijom'),
 15:('B','Deformacije rudarskog područja, UAV fotogrametrija kao pomoćni podatak'), 16:('A','Detekcija šumskih požara dronovima'),
 17:('A','Populacija špiljske ribe, dronovi u nepristupačnim galerijama'), 18:('A','Detekcija kompostnih hrpi (zaštita voda) UAV-om'),
 19:('A','Pregled kartiranja mikroklime u šumarstvu, uklj. dronove'), 20:('C','Književni tekst'),
 21:('A','Dronovi za praćenje bioraznolikosti Amazone'), 22:('C','Vojna detekcija ljudi; šuma samo kao okolina'),
 23:('B','Šteta na uljanoj repici (osiguranje)'), 24:('B','DEM iz UAV/LiDAR za rizik poplave (hidrologija/hazard)'),
 25:('A','UAS u upravljanju šumama Miombo'), 26:('A','Mali UAS za popise divljači'),
 27:('B','Korovi u soji'), 28:('C','Poduzetništvo s dronovima'),
 29:('A','Pregled UAV sustava za praćenje kakvoće zraka'), 30:('C','FinTech; nema UAV pojma u naslovu/sažetku'),
 31:('A','Dron vs. terenski popis vodenih ptica'), 32:('A','Beluge, dronski popisi'),
 33:('B','TLS segmentacija stabala; UAV spomenut kao proširenje'), 34:('B','Kartiranje prašuma GEDI; sažetak nedostupan (provjeriti)'),
 35:('C','Sigurnost kvadkoptera'), 36:('A','Dron za nadzor onečišćenja zraka'),
 37:('B','Zrelost soje'), 38:('A','Kakvoća vode u neformalnim naseljima; UAV preporučen'),
 39:('B','Šećerna repa, brojanje sadnica'), 40:('B','Urbani potoci; sažetak nedostupan (provjeriti)'),
 41:('B','Fenotipizacija pšenice'), 42:('C','Motor vojnog UAV-a'),
 43:('C','Dostava u uredima'), 44:('A','Termalni refugiji salmonida; dronske termalne kamere'),
 45:('B','Filtriranje DEM-a (geoznanosti)'), 46:('A','Krokodili, dronski monitoring'),
 47:('B','Fenotipizacija graha (skup podataka)'), 48:('B','Klizišta Brunei; sažetak nedostupan (provjeriti)'),
 49:('C','Podvodni dronovi (nisu UAV)'), 50:('A','Slana močvara, UAV multispektralno'),
 51:('B','Segmentacija vegetacije u poljoprivrednim poljima'), 52:('A','Višekratni UAV LiDAR za analizu vegetacije'),
 53:('A','Evolucija obalnih dina, dronska fotogrametrija'), 54:('A','Ptice štetnice, sukob divljači i poljoprivrede, dronovi'),
 55:('B','Urbana klasifikacija ortofota'), 56:('A','Klasifikacija vrsta drveća, UAV LiDAR'),
 57:('A','Detekcija požara; dronske snimke'), 58:('C','Sigurnost decentraliziranih mreža'),
 59:('C','Podvodni dronovi'), 60:('C','Regulativa dronova u EU (bez okolišne primjene)'),
 61:('B','Vinogradi, vodni status'), 62:('B','UAV kartiranje za usmjeravanje poplava (hidrologija)'),
 63:('B','Urbana klasifikacija UAV multispektralnih snimaka'), 64:('B','Prinos kukuruza'),
 65:('A','Dronovi za kalibraciju mjerenja obalnih struja'), 66:('A','Dronsko promatranje višerazinskih društava životinja'),
 67:('B','Rajčica, vodni status'), 68:('A','Onečišćenje mora naftom, dronovi'),
 69:('A','Volumen sastojine, UAS'), 70:('A','Ptice u mangrovama, dronovi'),
 71:('B','NDVI riže, dron s kamerom'), 72:('A','Detekcija šumskih požara dronskim snimkama'),
 73:('B','UAV LiDAR za geomorfološke promjene'), 74:('B','Detekcija promjena u UAV videu (generičko)'),
 75:('C','Generički pregled dronova (vojne primjene)'), 76:('A','Klasifikacija vrsta drveća, UAV hiperspektralno'),
 77:('B','Bolest kikirikija'), 78:('B','Kakvoća krme travnjaka (poljoprivreda)'),
 79:('A','Segmentacija stabala UAV LiDAR, ekosustavne usluge šuma'), 80:('B','Pepelnica pšenice'),
 81:('B','Razdvajanje usjeva'), 82:('B','Hiperspektralni senzor za šume i poljoprivredu (instrument)'),
 83:('B','Scenariji poplavljivanja otoka, UAV DTM'), 84:('B','Fenotipizacija durum pšenice'),
 85:('C','Prostorno planiranje (Indonezija)'), 86:('B','Geokonzervacija iskopa, UAS za snimanje'),
 87:('C','Testiranje softvera UAS-a'), 88:('A','Detekcija pojedinačnih stabala UAV LiDAR'),
 89:('B','Zone upravljanja tlom, pšenica'), 90:('A','Plimne ravnice, UAV 3D rekonstrukcija'),
 91:('A','UAV sustav za praćenje zraka i vode'), 92:('A','Inventura šume zmajeva stabla'),
 93:('A','Morski otpad, UAV detekcija'), 94:('B','Obalno polje vjetra mjereno UAV-om (meteorologija)'),
 95:('C','Urbanističko planiranje 3D'), 96:('B','Suzbijanje korova UAS'),
 97:('C','Književna studija (drone warfare)'), 98:('C','„UAs“ = used ampoules'),
 99:('A','Ekološki popis divljih svinja dronovima'), 100:('B','Dušik u riži, UAV hiperspektralno'),
}
S50 = {
 1:('A','Upravljanje požarima, UAV izviđanje'), 2:('A','Lokalizacija izvora plina mikro-UAV-om (okolišni monitoring)'),
 3:('A','Prilaz pticama dronovima, etičke smjernice'), 4:('A','Promjena uporabe zemljišta, UAV snimke'),
 5:('C','Vojne/sigurnosne primjene snimaka'), 6:('B','Rano suzbijanje korova'),
 7:('B','Karotenoidi u vinogradu'), 8:('A','Vodene ptice i obalna staništa, mali UAS'),
 9:('A','Kartiranje povremenog vodotoka UAS-om'), 10:('A','Pregled: UAS u istraživanju divljači'),
 11:('A','Cijanobakterije u jezeru Taihu, UAV'), 12:('A','Termalne UAV snimke za ekološke lokacije'),
 13:('A','Atmosferski profil u maglenoj šumi, UAV'), 14:('C','Arhitektonski projekt, geomatika'),
 15:('C','„Drone“ = trut (Apis dorsata)'), 16:('A','Geoekološki uvjeti obale, UAV fotogrametrija'),
 17:('B','Analiza krajobraza/planiranje (Koreja)'), 18:('C','Rimske zidine, kulturna baština'),
 19:('A','Viševrsni popis divljači UAV-om'), 20:('C','Detekcija kvarova UAV-a'),
 21:('A','Mjerenje šumskih požara UAS-om'), 22:('C','Nema UAV pojma (Fellowship of the Snow)'),
 23:('B','UAV kao platforma za IR snimanje (primjena nejasna)'), 24:('C','„UAS“ = Universidad Autónoma de Sinaloa'),
 25:('B','Praćenje vegetacije za upravljanje usjevima'), 26:('A','Gnijezda čimpanzi i plodonosna stabla, UAV'),
 27:('A','Vegetacija plimne ravnice, UAV snimke'), 28:('A','Mjerenja stakleničkih plinova s Global Hawk UAV-a'),
 29:('A','Popis vegetacije privatnog zemljišta, UAV'), 30:('C','MEMS IMU za navigaciju UAV-a'),
 31:('C','Stare utvrde, fotogrametrija baštine'), 32:('B','Fenotipizacija, digitalna poljoprivreda'),
 33:('A','Inventura malih šumskih površina UAS-om'), 34:('A','Detekcija curenja plina (metan) laserskim senzorom na UAV-u'),
 35:('A','Sustav praćenja vegetacije malim UAV-om'), 36:('A','Kartiranje pojedinačnih stabala bukove šume'),
 37:('A','Kartiranje raspodjele plina mikro-dronom'), 38:('B','UAV za preciznu poljoprivredu'),
 39:('B','Snježna opažanja, UAV snimanje kao pomoćni podatak'), 40:('C','Nema UAV pojma (Forestry Reports)'),
 41:('C','Platforme lakše od zraka; UAV samo spomenut'), 42:('A','Fotogrametrija kitova UAS-om'),
 43:('A','Planiranje putanje UAV-a za praćenje voda'), 44:('C','Nema UAV pojma (The Dulcimore)'),
 45:('A','Sustav praćenja šumskih požara mini-UAV-om'), 46:('A','UAS + biologging u prostornoj ekologiji'),
 47:('C','„UAS“ = sveučilišna kafeterija'), 48:('A','Konzervacijski dronovi u ekologiji'),
 49:('C','Upravljanje bespilotnim helikopterom'), 50:('C','Geodetska izmjera UAV-om (bez okolišne primjene)'),
}
