# -*- coding: utf-8 -*-
# Hrvatska verzija rada za MIPRO predložak. Oznake: {i:..} kurziv, {b:..} podebljano, {sup:..}, {sub:..}

TITLE = 'Dronovi u ekologiji i praćenju stanja okoliša: bibliometrijski pregled stanja i predviđanje rasta do 2035.'
AUTHORS = 'Marko Jelić*, Vedran Uroš{sup:†}'
AFFILS = ['* Veleučilište „Marko Marulić“ u Kninu, Knin, Hrvatska', '{sup:†} Fakultet organizacije i informatike, Sveučilište u Zagrebu, Varaždin, Hrvatska']
EMAIL = '* mjelic99@gmail.com'

ABSTRACT = ('Bespilotne letjelice (UAV) prešle su put od nišnog istraživačkog alata do standardne senzorske platforme u ekologiji i '
            'zaštiti okoliša, ali brzina te prihvaćenosti i njezino vjerojatno zasićenje dosad nisu kvantificirani. Iz otvorenog '
            'bibliografskog indeksa OpenAlex prikupili smo godišnji broj recenziranih radova koji spajaju pojmove o UAV-ima s ekološkim '
            'i okolišnim pojmovima za razdoblje 2005.–2025. (20 344 rada), zajedno s tri normalizacijska nazivnika i šest primjenskih '
            'poddomena, te smo u MATLAB-u, bez dodatnih alatnih paketa, Poissonovom devijancom prilagodili četiri modela rasta '
            '(eksponencijalni, logistički, Gompertzov i Bassov difuzijski). Modeli su uspoređeni kvazi-likelihood informacijskim '
            'kriterijem, provjereni retrospektivnim testiranjem s pomičnim ishodištem i bootstrapom za intervale predviđanja. '
            'Produkcija je rasla 29,3 posto godišnje (28 radova 2005., 4 747 radova 2025.), sa strukturnim lomom 2010. Apsolutna '
            'produkcija još ne pokazuje zasićenje: prosjek modela predviđa 8 466 radova 2028. [90-postotni interval 5 996–10 303]. Na deset '
            'godina modeli se razilaze, a dugoročno predviđanje brojeva usklađeno s analizom udjela jest prosjek triju zasićujućih modela: 17 058 radova 2035. [4 056–42 253]. Udio okolišne literature koja koristi UAV-e, '
            'međutim, jasno se zasićuje: logistički model s težinom 0,999 daje plato od 13,3 rada na 1 000 (13,0 bez dijelom artefaktnog opažanja za 2025.), od čega je 85 posto '
            'dosegnuto 2025. Rast se seli iz zrelih primjena (brojanje divljih životinja) u poddomene s otvorenim senzorskim problemima '
            '(zdravlje šuma, emisije plinova, požari). Raspravljaju se implikacije za konstrukciju i autonomiju UAV-a.')
KEYWORDS = 'bespilotne letjelice, praćenje stanja okoliša, bibliometrija, predviđanje tehnologije, modeli rasta, ekologija'

SECTIONS = [
('h1', 'Uvod'),
('p', 'Lake bespilotne letjelice (UAV, također UAS ili RPAS) najavljene su kao revolucija za prostornu ekologiju prije više od desetljeća [1], [2]. Otada se koriste za brojanje divljih životinja, kartiranje šteta u šumama, procjenu kakvoće vode, kvantifikaciju emisija plinova i nadzor zaštićenih područja, a specijalizirani pregledi danas navode stotine primjena [3]. Za robotičku zajednicu koja te platforme projektira ostaju otvorena dva pitanja. Prvo, koliko brzo prihvaćanje UAV-a u ekologiji i zaštiti okoliša zaista raste kad se uzme u obzir rast cjelokupne znanstvene literature? Drugo, je li taj rast još eksponencijalan ili se približava zasićenju, i što odgovor znači za to kamo bi se u idućem desetljeću trebali usmjeriti senzorika, autonomija i regulatorni napori?'),
('p', 'Ovaj rad odgovara na oba pitanja reproducibilnom bibliometrijskom vremenskom serijom i transparentnim postupkom predviđanja. Naši su doprinosi: (i) javno dohvatljiv godišnji skup podataka (2005.–2025.) o istraživanjima UAV-a u ekologiji i zaštiti okoliša, s tri nazivnika i šest primjenskih poddomena, izgrađen iz indeksa OpenAlex [4]; (ii) opis trenutnog stanja područja, uključujući testove trenda, strukturni lom i raspodjelu produkcije po poddomenama, zemljama i časopisima; (iii) MATLAB algoritam bez ovisnosti o alatnim paketima koji prilagođava i uspoređuje četiri klasična modela rasta, provjerava ih izvan uzorka i daje bootstrap predviđanja za horizonte od 3, 5, 7 i 10 godina; te (iv) raspravu o tome što predviđanja znače za inženjere UAV-a, uokvirenu dokazima o točnosti dostupnima za svaku primjenu i europskim regulatornim kontekstom.'),
('p', 'Rad je organiziran kako slijedi. Odjeljak II daje pregled dokaza o performansama UAV-a u okolišnim primjenama i tradicije krivulja rasta u predviđanju tehnologije. Odjeljak III opisuje podatke i algoritam. Odjeljak IV izvještava rezultate, a odjeljak V ih raspravlja. Odjeljak VI zaključuje.'),

('h1', 'Srodni radovi'),
('p', 'Ekološki argument za UAV-e počiva na izmjerenim dobicima u točnosti. U kontroliranom pokusu s replikama kolonija morskih ptica poznate veličine, brojanje iz UAV snimaka bilo je 43 do 96 posto točnije od brojanja iskusnih promatrača sa zemlje, a poluautomatsko brojanje zadržalo je tu točnost [5]. U šumarstvu su multitemporalne hiperspektralne i multispektralne UAV snimke razdvojile zdrave, zaražene i mrtve smreke s ukupnom točnošću od 76 do 81 posto, ali otkrivanje u operativno korisnoj fazi „zelenog napada“ ostaje težak problem [6]. U kopnenim vodama multispektralni UAV podaci procjenjuju klorofil-a s koeficijentima determinacije od 0,79 do 0,98, a izravna usporedba multispektralnog i hiperspektralnog senzora na istim ribnjacima pokazala je trostruku razliku u pogrešci za cijanobakterije [7]. Za emisije metana pregled UAV metoda kvantifikacije izvijestio je o procjenama toka koje se između metoda primijenjenih na isti izvor razlikuju četverostruko [8]. UAV-i su ujedno novi izvor uznemiravanja: sustavni pregled utvrdio je da ciljano usmjereni obrasci leta, veće letjelice i motori s unutarnjim izgaranjem izazivaju najjače reakcije divljih životinja te da ptice reagiraju češće od ostalih svojti [9]. Ti su rezultati ovdje važni jer pokazuju koja su područja primjene tehnički zrela, a koja nisu, što se pokazuje kao objašnjenje stopa rasta po poddomenama u odjeljku IV.'),
('p', 'Predviđanje prihvaćanja tehnologije krivuljama rasta ima dugu tradiciju. Bassov difuzijski model [10] opisuje usvajanja po razdoblju kao zbroj učinaka inovacije i imitacije; logistička i Gompertzova krivulja opisuju kumulativne razine ili razine po razdoblju koje se približavaju gornjoj granici; pregled područja kroz 25 godina zaključio je da nijedna krivulja ne dominira te preporučio kombiniranje modela i izvještavanje o nesigurnosti modela [11]. Broj publikacija široko se koristi kao zamjenska mjera prihvaćanja, uz ogradu da cjelokupna znanstvena literatura i sama raste nekoliko posto godišnje [12], pa nenormalizirani brojevi precjenjuju rast svake teme. Višemodelno zaključivanje s Akaikeovim težinama [13] daje načelan način kombiniranja konkurentskih krivulja. Slijedimo te preporuke: prilagođavamo četiri modela, normaliziramo rastom područja, ponderiramo modele kvazi-likelihood informacijskim kriterijem i izvještavamo intervale koji uključuju nesigurnost modela.'),

('h1', 'Podaci i metode'),
('h2', 'Bibliometrijski korpus'),
('p', 'Podaci su dohvaćeni 26. kolovoza 2026. iz REST API-ja baze OpenAlex [4], agregirani po godini objave (krajnja točka /works, group_by=publication_year), s tipom dokumenta ograničenim na članke i preglede. Osnovni upit D AND E pretraživao je naslove i sažetke, pri čemu je D = (drone OR drones OR UAV OR UAVs OR UAS OR "unmanned aerial" OR "unmanned aircraft" OR RPAS OR "remotely piloted aircraft"), a E je disjunkcija 24 ekološka i okolišna pojma (ecology, wildlife, biodiversity, habitat, ecosystem, forest, vegetation, "water quality", "air quality", "greenhouse gas", methane, "protected area", wetland, coastal, marine, wildfire i njihove inačice). Tri nazivnika dohvaćena su s identičnim filtrima: samo E (okolišna literatura pretražena na isti način, korištena kao primarni nazivnik), OpenAlex polje Environmental Science (klasifikacijski nazivnik) i sva indeksirana djela; sva tri koriste se u analizi udjela (odjeljak IV.C). Dohvaćena je i kontekstna serija samo D (cjelokupna UAV literatura), koja se koristi isključivo za izvještavanje okolišnog udjela UAV istraživanja. Šest preklapajućih poddomenskih upita kombiniralo je D s pojmovima za popise divljih životinja, zdravlje šuma, kakvoću vode, zrak i emisije plinova, požare te zaštićena područja i suzbijanje krivolova. Budući da se OpenAlex retroaktivno ažurira, datum dohvata dio je definicije podataka; točni Booleovi izrazi i kodna knjiga priloženi su uz MATLAB kod.'),
('p', 'Prozor prilagodbe je 2005.–2025. (n = 21 potpuna godina); 2026. je nepotpuna i isključena je. Tri ograničenja treba navesti. OpenAlex je širi od Scopusa ili Web of Science, pa su apsolutni brojevi veći nego što bi ih te baze dale, dok su trendovi i udjeli usporedivi. Upit nije savršeno precizan. U ručnoj provjeri slučajnog uzorka od 100 zapisa (OpenAlex sample, seed 20260826), kodiranog uz pomoć AI i neovisno pregledanog od drugog autora (slaganje 78 posto, Cohenova kappa 0,64), 60 posto [Wilsonov 95-postotni CI 50, 69] bile su UAV studije u ekologiji, praćenju okoliša ili praćenju vegetacije i agroekosustava, daljnja 24 posto koristila su UAV u neokolišnoj primjeni (urbanistička izmjera, sigurnost, dostava, konstrukcija platforme), a 16 posto bio je šum („drone“ kao trut, „UAS“ kao drugi akronim, radovi bez UAV-a). U uzorku iz ranog razdoblja (2005.–2015., n = 50) relevantni udio bio je 68 posto [54, 79]; razlika nije značajna (dvoproporcijski z = 0,95, p = 0,34). Stroži upit koji isključuje poljoprivredne pojmove raste 27,9 umjesto 29,3 posto godišnje, pa su zaključci o trendu robusni na tu nepreciznost, dok apsolutne brojeve treba čitati kao zapise OpenAlexa pogođene upitom, a ne kao točne brojeve okolišnih UAV studija; svaka vrijednost korigirana preciznošću (oko 0,6 puta sirovih brojeva) procjena je, a ne ispravljen broj. Kodirani uzorci priloženi su u repozitoriju. Naposljetku, sve serije skaču 2025. (okolišni nazivnik za 39 posto), što je dijelom artefakt indeksiranja; normalizacija ga ublažava, a izvještava se i analiza osjetljivosti bez 2025.'),
('h2', 'Deskriptivna analiza'),
('p', 'Za brojeve {i:y{sub:t}} i udio {i:s{sub:t}} = 1000 {i:y{sub:t}}/{i:N{sub:t}} (radova na 1 000 okolišnih radova) izvještavamo složenu godišnju stopu rasta, Mann–Kendallov test trenda s korekcijom za vezane vrijednosti i Senov nagib s 90-postotnim intervalom pouzdanosti [14], [15], te segmentiranu log-linearnu regresiju s jednom prijelomnom točkom pronađenom pretragom po mreži i testiranom naspram jednog nagiba F-testom Chowova tipa (približnim, jer je prijelomna točka procijenjena).'),
('h2', 'Modeli rasta'),
('p', 'Prilagođena su četiri modela očekivane godišnje produkcije {i:μ}({i:t}), uz {i:τ} = {i:t} − 2005:'),
('eq', '{i:μ}({i:t}) = {i:a} exp({i:b τ})', 1),
('eq', '{i:μ}({i:t}) = {i:K} / [1 + exp(−{i:r}({i:τ} − {i:t{sub:m}}))]', 2),
('eq', '{i:μ}({i:t}) = {i:K} exp[−exp(−{i:r}({i:τ} − {i:t{sub:m}}))]', 3),
('eq', '{i:μ}({i:t}) = {i:m} [{i:F}({i:τ}+1) − {i:F}({i:τ})]', 4),
('p', 'gdje je (1) eksponencijalni rast bez zasićenja, (2) logistička i (3) Gompertzova krivulja s kapacitetom {i:K}, stopom {i:r} i godinom infleksije {i:t{sub:m}}, a (4) Bassov difuzijski model [10] s tržišnim potencijalom {i:m}, koeficijentom inovacije {i:p} i koeficijentom imitacije {i:q}, pri čemu je {i:F}({i:x}) = [1 − e{sup:−({i:p}+{i:q}){i:x}}] / [1 + ({i:q}/{i:p}) e{sup:−({i:p}+{i:q}){i:x}}] kumulativni udio usvajanja. Za udio iste krivulje opisuju stopu {i:g}({i:t}) s nazivnikom kao offsetom, {i:μ{sub:t}} = {i:N{sub:t}} {i:g}({i:t}), pa predviđanja udjela ne zahtijevaju predviđanje nazivnika; Bassov model izostavljen je za udio jer opisuje usvajanja po razdoblju, a ne razinu.'),
('h2', 'Procjena, izbor modela i nesigurnost'),
('p', 'Parametri su procijenjeni minimiziranjem Poissonove devijance'),
('eq', '{i:D} = 2 Σ{sub:{i:t}} [{i:y{sub:t}} ln({i:y{sub:t}}/{i:μ{sub:t}}) − ({i:y{sub:t}} − {i:μ{sub:t}})]', 5),
('p', 'Nelder–Meadovim simpleksom (MATLAB fminsearch) iz više početnih točaka, s log-transformiranim pozitivnim parametrima. Devijanca je prirodni analog najmanjih kvadrata za brojeve: daje usporedivu težinu malim ranim i velikim kasnim godinama i daje pravi log-likelihood za informacijske kriterije. Brojevi su jako predisperzirani (Pearsonova disperzija ĉ = 19,8 za brojeve, 13,1 za udio), pa su modeli uspoređeni kvazi-likelihood kriterijem za male uzorke'),
('eq', 'QAIC{sub:c} = −2 ln {i:L} / ĉ + 2{i:k} + 2{i:k}({i:k}+1)/({i:n}−{i:k}−1)', 6),
('p', 'i kombinirani Akaikeovim težinama [13]. Točnost izvan uzorka procijenjena je retrospektivnim testiranjem s pomičnim ishodištem: svaki je model ponovno prilagođen na podacima do 2018., 2020. i 2022. i ocijenjen na preostalim godinama srednjom apsolutnom postotnom pogreškom (MAPE) [16]. Nesigurnost predviđanja dobivena je parametarskim negativno-binomnim bootstrapom: za svaki je model 1 000 repliciranih serija generirano kao gama–Poissonova mješavina oko prilagođenih vrijednosti s disperzijom procijenjenom metodom momenata, svaki je model ponovno prilagođen na svakoj replici, težine QAIC{sub:c} ponovno su izračunate i ponderirano predviđanje zabilježeno, što daje 90-postotne intervale koji uključuju i parametarsku nesigurnost i nesigurnost modela. Izvješteni prosjek modela medijan je te bootstrap distribucije ponderiranih predviđanja; budući da se težine ponovno računaju na svakoj replici, on nije identičan QAIC{sub:c}-ponderiranoj kombinaciji točkastih predviđanja iz tablica I i II, a razlika raste s horizontom jer replike koje podupiru eksponencijalni oblik vuku distribuciju prema gore. Pogreške retrospektivnog testa izvještavaju se i po ishodištu i usrednjeno, jer ishodišta odgovaraju sedmo-, peto- i trogodišnjem horizontu evaluacije. Predviđanja se izvještavaju za 2028., 2030., 2032. i 2035., tj. 3, 5, 7 i 10 godina nakon posljednje prilagođene godine. Postupak (deset MATLAB funkcija, bez alatnih paketa, izvršiv i u GNU Octaveu) neovisno je repliciran u Pythonu; procjene parametara i devijance podudaraju se u svim izvještenim znamenkama.'),

('h1', 'Rezultati'),
('h2', 'Trenutno stanje'),
('p', 'Godišnja produkcija porasla je s 28 radova 2005. na 4 747 radova 2025., što je složena godišnja stopa rasta od 29,3 posto za cijelo razdoblje i 30,6 posto za posljednjih deset godina; u razdoblju 2005.–2025. objavljena su 20 344 rada. Mann–Kendallov test je nedvosmislen ({i:S} = 209, {i:Z} = 6,28, {i:p} = 3 × 10{sup:−10}), sa Senovim nagibom od 147 radova godišnje [90-postotni CI 105, 194]. Segmentirana regresija locira lom u 2010.: rast se ubrzao sa 17 na 34 posto godišnje ({i:F} = 5,5, {i:p} ≈ 0,014, približno), što se poklapa s pojavom jeftinih višerotorskih platformi i MEMS senzora, a ne s regulacijom. Normaliziran okolišnom literaturom, udio je porastao s 0,34 na 11,27 radova na 1 000 (Senov nagib 0,60 na 1 000 godišnje [0,49, 0,76]); unutar cjelokupne literature o UAV-ima ekološki i okolišni dio porastao je s 2,9 na 18,5 posto.'),
('p', 'Produkcija je koncentrirana: Kina (4 410 radova s barem jednim kineskim autorom), Sjedinjene Američke Države (3 470), Ujedinjeno Kraljevstvo (1 015), Njemačka (855) i Indija (813) predvode 182 zemlje sudionice; Hrvatska je pridonijela 62 rada, sve od 2016. Vodeći su časopisi Remote Sensing (1 709), Drones (494), ISPRS Archives (423), Sensors (355) i Forests (307); 72 posto korpusa je u otvorenom pristupu, a 910 radova ima više od 99 citata. Slika 1 prikazuje poddomene. U razdoblju 2015.–2025. najzrelija primjena, brojanje divljih životinja, rasla je najsporije (sa 100 na 547 radova, 18,5 posto godišnje), dok je zdravlje šuma raslo najbrže (sa 114 na 2 079, 33,7 posto), a slijede zaštićena područja i suzbijanje krivolova (29,6 posto), požari (28,3 posto), zrak i emisije plinova (26,8 posto) te kakvoća vode (25,8 posto).'),
('fig', 'fig3', 'Godišnji broj radova u OpenAlexu koji kombiniraju pojmove o UAV-ima sa šest okolišnih poddomena, 2005.–2025. (logaritamska skala; poddomenski se upiti preklapaju).'),
('h2', 'Modeli rasta godišnje produkcije'),
('p', 'Tablica I uspoređuje četiri modela prilagođena godišnjim brojevima. Nijedan model nije odlučno bolji: težine QAIC{sub:c} kreću se od 0,08 (eksponencijalni) do 0,41 (Gompertz), a modeli sa zasićenjem ne slažu se oko gornje granice. Logistički model smješta točku infleksije u 2025.–2026. s kapacitetom od oko 9 700 radova godišnje, Bassov model doseže vrhunac 2029. i zatim pada, a Gompertzova prilagodba degenerira prema eksponencijalnom obliku (kapacitet u milijunima, infleksija 2086.). Retrospektivno testiranje potvrđuje da podaci još ne mogu razdvojiti te oblike. Po ishodištima, MAPE iznosi 41–43 posto od 2018. (sedam preostalih godina), 56–58 posto od 2020. i 15–35 posto od 2022. (tri preostale godine); svaki prozor sadrži dijelom artefaktnu 2025. Od najnovijeg ishodišta logistički je model najbolji (15 posto), a eksponencijalni najlošiji (35 posto); usrednjeno preko ishodišta svi su modeli na 39–45 posto.'),
('table', 'Modeli rasta prilagođeni godišnjem broju radova, 2005.–2025.',
    [950, 250, 800, 700, 640, 1396],
    ['Model', '{i:k}', 'Devijanca', 'QAIC{sub:c}', 'Težina', 'Parametri'],
    [['Eksponencijalni', '2', '469,5', '36,5', '0,083', '{i:a} = 27,5, {i:b} = 0,256 (29,2 %/god.)'],
     ['Logistički', '3', '364,9', '33,9', '0,296', '{i:K} = 9 739, {i:r} = 0,302, {i:t{sub:m}} = 2025,9'],
     ['Gompertz', '3', '352,2', '33,3', '0,408', '{i:K} = 3,7 × 10{sup:6}, {i:r} = 0,031, {i:t{sub:m}} = 2086'],
     ['Bass', '3', '377,9', '34,6', '0,213', '{i:m} = 88 560, {i:p} = 1,8 × 10{sup:−4}, {i:q} = 0,294']],
    ['left', 'center', 'center', 'center', 'center', 'left']),
('p', 'Slika 2 prikazuje prilagodbe i predviđanja, a tablica II ih navodi. Modeli se slažu za trogodišnji horizont (6 100 do 10 000 radova 2028.; prosjek modela 8 466 [90-postotni interval 5 996, 10 303]) i nakon toga se razilaze: 2035. točkasta predviđanja sežu od 3 681 (Bass) do 59 923 (eksponencijalni). Puni prosjek modela doseže 35 872 [10 232–62 285], ali se na tom horizontu oslanja na eksponencijalni model, koji analiza udjela odbacuje (odjeljci IV.C i V.A). Tablica II stoga navodi i prosjek triju zasićujućih modela (renormalizirane težine 0,32, 0,45 i 0,23), koji 2035. doseže 17 058 radova [4 056–42 253] i predstavlja dugoročno predviđanje brojeva korišteno u ostatku rada. Analiza osjetljivosti objašnjava širinu: bez opažanja za 2025. logistički kapacitet pada s 9 739 na oko 4 400, a Bassov model predviđa pad, pa jedna jedina godina, koja je dijelom artefakt indeksiranja, udvostručuje procijenjenu gornju granicu.'),
('fig', 'fig1', 'Godišnji broj radova u OpenAlexu koji kombiniraju pojmove o UAV-ima i ekologiji ili okolišu (točke), četiri modela rasta prilagođena Poissonovom devijancom (linije) te QAIC{sub:c}-ponderirani prosjek modela s 90-postotnim negativno-binomnim bootstrap intervalom (kvadrati, osjenčano) za 2028.–2035.'),
('table', 'Predviđena godišnja produkcija: točkaste procjene i 90-postotni bootstrap intervali prosjeka modela',
    [1000, 934, 934, 934, 934],
    ['Model', '2028.', '2030.', '2032.', '2035.'],
    [['Eksponencijalni', '9 966', '16 639', '27 779', '59 923'],
     ['Logistički', '6 364', '7 551', '8 409', '9 154'],
     ['Gompertz', '7 920', '11 494', '16 309', '26 505'],
     ['Bass', '6 147', '6 474', '5 760', '3 681'],
     ['{b:Prosjek modela}', '{b:8 466}', '{b:12 775}', '{b:19 195}', '{b:35 872}'],
     ['90 % interval', '5 996–10 303', '7 198–17 218', '8 241–28 683', '10 232–62 285'],
     ['{b:Prosjek zasićujućih}', '{b:7 133}', '{b:9 443}', '{b:12 051}', '{b:17 058}'],
     ['90 % interval', '5 215–9 502', '5 409–14 717', '5 137–22 336', '4 056–42 253']],
    ['left', 'center', 'center', 'center', 'center']),
('h2', 'Udio u okolišnoj literaturi'),
('p', 'Slika je drukčija, i mnogo jasnija, za udio (slika 3). Logistički model stope dobiva praktički svu težinu (0,999; eksponencijalni je model odbačen s razlikom QAIC{sub:c} od 46) i procjenjuje plato od {i:K} = 13,3 rada na 1 000 okolišnih radova s infleksijom 2019.–2020. Udio opažen 2025., 11,3 na 1 000, već je 85 posto tog platoa. Prosjek modela predviđa 13,1 na 1 000 u 2028. [12,1, 14,7], 13,9 u 2030. [12,6, 16,8] i 15,4 u 2035. [13,1, 21,7], pri čemu gornji rep potječe od malog preostalog udjela Gompertzove krivulje. Retrospektivno testiranje od ishodišta 2022. daje MAPE od 10,6 posto za logistički model naspram 58 posto za eksponencijalni. Drugim riječima, uporaba UAV-a u okolišnim istraživanjima prestala je rasti brže od područja: nakon 2020. raste zajedno s njim. Plato je robustan u tri smjera. Bez opažanja za 2025. logistički model i dalje dobiva praktički svu težinu (0,997), a plato se pomiče tek s 13,3 na 13,0 na 1 000, od čega je 80 posto bilo dosegnuto već 2024. — normalizacija dakle upija najveći dio artefakta indeksiranja iz 2025. koji dominira modelima brojeva. Uz klasifikacijski nazivnik (OpenAlex polje Environmental Science) logistički model opet dominira (težina 0,96; plato 19,0 na 1 000, infleksija 2023., 68 posto dosegnuto 2025.), a jednako i uz sva indeksirana djela (težina 0,96; plato 1,12 na 1 000, infleksija 2024., 59 posto dosegnuto). Zasićujući oblik stoga je neovisan o nazivniku, dok je točan položaj na krivulji — onih „85 posto“ — specifičan za nazivnik okolišne literature.'),
('fig', 'fig2', 'Udio radova povezanih s UAV-ima na 1 000 okolišnih radova (OpenAlex), prilagođeni eksponencijalni, logistički i Gompertzov model stope s okolišnom literaturom kao offsetom te QAIC{sub:c}-ponderirano predviđanje s 90-postotnim bootstrap intervalom.'),

('h1', 'Rasprava'),
('h2', 'Što dva predviđanja znače zajedno'),
('p', 'Apsolutna produkcija i udio pričaju jednu priču, a ne dvije. Sama okolišna literatura porasla je u istom indeksu s 82 000 na 421 000 radova godišnje između 2005. i 2025., pa bi okolišna UAV literatura koja zadržava stalan udio od 13 na 1 000 i dalje rasla stopom područja, što je upravo ono što logistički i Gompertzov model brojeva opisuju. Nastavi li okolišna literatura rasti stopom iz 2015.–2024. od 6,6 posto godišnje (2025. je isključena kao dijelom artefaktna), predviđanje udjela od 13,1–21,7 na 1 000 implicira otprilike 10 500–17 400 radova 2035. — raspon koji obuhvaća prosjek zasićujućih modela od 17 058 iz tablice II, pa se dva pristupa predviđanju slažu čim se eksponencijalni model ostavi po strani. Taj model, koji bi ovisno o pretpostavljenom rastu nazivnika implicirao peterostruki do sedmerostruki porast udjela do 2035., u suprotnosti je s analizom udjela i treba ga za duge horizonte odbaciti unatoč njegovoj nezanemarivoj težini na samim brojevima. Naše je čitanje dokaza stoga da je UAV dovršio prijelaz od nove istraživačke teme do standardne senzorske platforme te da pouzdan horizont predviđanja apsolutnog broja iznosi oko tri godine — pogreška retrospektivnog testa od najnovijeg ishodišta trećina je do polovine pogreške na peto- i sedmogodišnjem ishodištu; nakon toga pitanje „koja krivulja“ nadjačava svaku statističku nesigurnost, pa svako dugoročno predviđanje brojeva treba, kao u tablici II, izvještavati zajedno s analizom udjela koja ga sidri.'),
('h2', 'Implikacije za robotičku zajednicu'),
('p', 'Ako je platforma sada standardna, buduća vrijednost leži manje u „još jednoj primjeni UAV-a“, a više u senzorskim i autonomijskim zahtjevima poddomena koje još ubrzavaju, a dokazi o točnosti iz odjeljka II pokazuju koji su to zahtjevi. Brojanje divljih životinja, gdje UAV-i već nadmašuju ljude [5], najsporije je rastuća poddomena. Zdravlje šuma, najbrže rastuća, ograničeno je osjetljivošću ranog otkrivanja: multispektralne snimke pronalaze tek manjinu zaraženih stabala u fazi zelenog napada, a većinu tek kad je promjena boje već vidljiva [6], što traži hiperspektralne ili termalne senzore koji ostaju unutar masenog i energetskog proračuna malih višerotornih letjelica te planiranje ponovljenih preleta umjesto pojedinačnih snimanja. Kakvoća vode ograničena je konstrukcijom senzora: uobičajene multispektralne kamere nemaju pojas centriran na fikocijanin, pigment koji najbolje ukazuje na biomasu cijanobakterija [7]. Kvantifikacija emisija plinova ograničena je nesigurnošću: tokovi iz istog izvora razlikuju se četverostruko između metoda [8], pa obrasci leta koji sustavno uzorkuju poprečni presjek perjanice i procjena nesigurnosti toka na samoj letjelici vrijede više od još jednog senzora. Naposljetku, dokazi o uznemiravanju [9] izravno se prevode u pravila projektiranja: električni pogon, mali zrakoplovni okviri, prilazne putanje koje nisu usmjerene na cilj i visina prilagođena svojti i životnoj fazi. To su inženjerski problemi, a podaci o rastu pokazuju da će upravo tu biti okolišna potražnja za istraživanjima UAV-a u idućem desetljeću.'),
('h2', 'Operativni i regulatorni kontekst'),
('p', 'Rast publikacija nadmašio je rast operativne baze. U Sjedinjenim Američkim Državama nove komercijalne registracije UAV-a dosegle su vrhunac od oko 175 000 u 2018. i pale na oko 124 000 u 2024., dok je broj certifikata daljinskih pilota dosegao 493 000 u 2025. [17]. U Europi je Agencija Europske unije za sigurnost zračnog prometa 2025. izvijestila o više od dva milijuna registriranih operatora [18]; Španjolska je do kraja 2025. registrirala 150 332 operatora, što je godišnji porast od 26 posto. Hrvatska je 2024. imala 2 464 registrirana operatora UAS-a, 9 633 udaljena pilota i 18 odobrenja u „posebnoj“ kategoriji [19]. Otkako se Uredba (EU) 2019/947 primjenjuje od 31. prosinca 2020. [20], većina misija praćenja stanja okoliša pripada „otvorenoj“ kategoriji, ali snimanja velikih staništa izvan vidnog polja, koja su upravo ono što kartiranje zdravlja šuma i emisija zahtijeva, traže „posebnu“ kategoriju i procjenu rizika. U Hrvatskoj letovi u zaštićenim područjima dodatno zahtijevaju odobrenje javne ustanove koja područjem upravlja [21], a neki su nacionalni parkovi rekreativnu uporabu UAV-a posve zabranili. Područja u kojima bi UAV praćenje bilo najkorisnije ujedno su, dakle, područja s najstrože ograničenim pristupom, paradoks koji autonomija (pouzdano geografsko ograničavanje, konzervativni sigurnosni mehanizmi, tihi rad) može pomoći razriješiti.'),
('h2', 'Ograničenja'),
('p', 'Četiri ograničenja omeđuju zaključke. Prvo, korpus ovisi o jednom indeksu i jednom upitu čija je preciznost 60 posto, pa su apsolutni brojevi zapisi OpenAlexa pogođeni upitom, a ne točni brojevi okolišnih UAV studija; OpenAlex pokriva više regionalnih časopisa od Scopusa, a planirana je replikacija istog Booleova upita u Scopusu. Drugo, opažanje za 2025. dijelom je artefakt indeksiranja i nosi nerazmjernu težinu u modelima sa zasićenjem, kako pokazuje analiza osjetljivosti. Treće, poddomenski se upiti preklapaju i nisu ugniježđeni u osnovni upit, pa opisuju relativni rast, a ne particiju ukupnog broja. Četvrto, nesigurnost modela predstavljena je samo s četiri parametarska oblika; promjenu politike indeksiranja ili regulatorni šok nijedan od njih ne bi obuhvatio, a test prijelomne točke je približan. Registarske brojke heterogene su trenutačne snimke i koriste se samo kao kontekst.'),

('h1', 'Zaključak'),
('p', 'Reproducibilna bibliometrijska serija pokazuje da su istraživanja UAV-a u ekologiji i zaštiti okoliša rasla 29 posto godišnje između 2005. i 2025., sa strukturnim ubrzanjem 2010., te da se njihov udio u okolišnoj literaturi zasićuje na oko 13 radova na 1 000. Četiri modela rasta, prilagođena i usrednjena u MATLAB postupku bez alatnih paketa, slažu se oko trogodišnjeg predviđanja od otprilike 8 500 radova 2028.; na deset godina predviđanje brojeva usklađeno s analizom udjela — prosjek zasićujućih modela — doseže oko 17 000 radova 2035., uz širok interval. Predviđanje udjela robusno je i na opažanje za 2025. i na izbor nazivnika. Rast se seli iz zrelih primjena u poddomene s otvorenim problemima senzorike, nesigurnosti i autonomije, gdje robotička zajednica može dati najveći doprinos. Podaci, definicije upita i kod priloženi su uz rad kao javno arhivirani repozitorij [22] kako bi se analiza mogla ponoviti na bilo koji budući datum dohvata.'),
]

ACK = ('Autori su koristili alate generativne umjetne inteligencije (Anthropic Claude) za generiranje statističkog koda, skriptiranje dohvata podataka i jezično uređivanje. '
       'Sve analize izvršili su i provjerili autori, koji preuzimaju punu odgovornost za sadržaj.')

ABSTRACT_LABEL = 'Sažetak'; KEYWORDS_LABEL = 'Ključne riječi'; ACK_TITLE = 'Zahvala'; REF_TITLE = 'Literatura'
FIG_LABEL = 'Slika'; TABLE_LABEL = 'TABLICA'
from content import REFERENCES  # popis literature ostaje u izvornom (IEEE) obliku
