# -*- coding: utf-8 -*-
# Paper content for the MIPRO template. Markup: {i:..} italic, {b:..} bold, {sup:..}, {sub:..}

TITLE = 'Drones in Ecology and Environmental Monitoring: Bibliometric State of the Art and Growth Forecasts to 2035'
AUTHORS = 'Marko Jelić*, Vedran Uroš{sup:†}'
AFFILS = ['* University of Applied Sciences "Marko Marulić" in Knin, Knin, Croatia', '{sup:†} Faculty of Organization and Informatics, University of Zagreb, Varaždin, Croatia']
EMAIL = '* mjelic99@gmail.com'

ABSTRACT = ('Unmanned aerial vehicles (UAVs) have moved from a niche research tool to a standard sensing platform in ecology and '
            'environmental protection, yet the pace and the likely saturation of this adoption have not been quantified. We compiled '
            'annual counts of peer-reviewed articles combining UAV terms with ecological and environmental terms from the open '
            'bibliographic index OpenAlex for 2005 to 2025 (20,344 articles), together with three normalising denominators and six '
            'application sub-domains, and fitted four growth models (exponential, logistic, Gompertz and Bass diffusion) by Poisson '
            'deviance in a toolbox-free MATLAB pipeline. Models were compared with a quasi-likelihood information criterion, validated '
            'by rolling-origin backtesting and bootstrapped for forecast intervals. Output grew at 29.3 percent per year (28 articles in '
            '2005, 4,747 in 2025), with a structural break in 2010. Absolute output shows no saturation yet: the model average predicts '
            '8,466 articles in 2028 and 35,872 in 2035, but the ten-year interval spans 10,232 to 62,285 because the models disagree on '
            'the inflection point. The share of environmental literature that uses UAVs, however, is clearly saturating: a logistic '
            'model with weight 0.999 gives a plateau of 13.3 articles per 1,000, of which 85 percent was reached in 2025. Growth is '
            'shifting from mature applications (wildlife counting) to sub-domains with open sensing problems (forest health, gas '
            'emissions, wildfire). Implications for UAV design and autonomy are discussed.')
KEYWORDS = 'unmanned aerial vehicles, environmental monitoring, bibliometrics, technology forecasting, growth models, ecology'

SECTIONS = [
('h1', 'Introduction'),
('p', 'Lightweight unmanned aerial vehicles (UAVs, also UAS or RPAS) were announced as a revolution for spatial ecology more than a decade ago [1], [2]. Since then they have been used to count wildlife, map forest damage, estimate water quality, quantify gas emissions and patrol protected areas, and dedicated reviews now list hundreds of applications [3]. Two questions remain open for the robotics community that designs these platforms. First, how fast is the adoption of UAVs in ecology and environmental protection actually growing, once the growth of the whole scientific literature is taken into account? Second, is that growth still exponential, or is it approaching saturation, and what does the answer imply for where sensing, autonomy and regulatory effort should be directed over the next decade?'),
('p', 'This paper answers both questions with a reproducible bibliometric time series and a transparent forecasting pipeline. Our contributions are: (i) an openly queryable annual data set (2005–2025) of UAV research in ecology and environmental protection, with three denominators and six application sub-domains, built from the OpenAlex index [4]; (ii) a description of the current state of the field, including trend tests, a structural break and the distribution of output over sub-domains, countries and venues; (iii) a MATLAB algorithm, free of toolbox dependencies, that fits and compares four classical growth models, validates them out of sample and produces bootstrapped forecasts for 3, 5, 7 and 10-year horizons; and (iv) a discussion of what the forecasts mean for UAV engineers, framed by the accuracy evidence available for each application and by the European regulatory context.'),
('p', 'The paper is organised as follows. Section II reviews the evidence on UAV performance in environmental applications and the growth-curve tradition in technology forecasting. Section III describes the data and the algorithm. Section IV reports the results and Section V discusses them. Section VI concludes.'),

('h1', 'Related Work'),
('p', 'The ecological case for UAVs rests on measured accuracy gains. In a controlled experiment with replica seabird colonies of known size, counts from UAV imagery were 43 to 96 percent more accurate than counts by experienced ground observers, and semi-automated counting retained that accuracy [5]. In forestry, multitemporal hyperspectral and multispectral UAV imagery separated healthy, infested and dead Norway spruce with overall accuracies of 76 to 81 percent, but detection during the operationally useful "green attack" phase remains the hard problem [6]. In inland waters, UAV multispectral data estimate chlorophyll-a with coefficients of determination of 0.79 to 0.98, and a direct comparison of multispectral and hyperspectral sensors on the same ponds showed a threefold difference in cyanobacteria error [7]. For methane emissions, a review of UAV quantification methods reported flux estimates differing by a factor of four between methods applied to the same source [8]. UAVs are also a new source of disturbance: a systematic review found that target-oriented flight patterns, larger aircraft and fuel engines evoke the strongest reactions in wildlife, and that birds react more often than other taxa [9]. These results matter here because they identify which application areas are technically mature and which are not, a distinction that turns out to explain the sub-domain growth rates in Section IV.'),
('p', 'Growth-curve forecasting of technology adoption has a long tradition. The Bass diffusion model [10] describes adoption per period as the sum of innovation and imitation effects; logistic and Gompertz curves describe cumulative or per-period levels approaching a ceiling; a 25-year review of the field concluded that no single curve dominates and recommended combining models and reporting model uncertainty [11]. Publication counts are widely used as an adoption proxy, with the caveat that the whole scientific literature itself grows at several percent per year [12], so that unnormalised counts overstate the growth of any topic. Multimodel inference with Akaike weights [13] provides a principled way to combine competing curves. We follow these recommendations: we fit four models, normalise by the growth of the field, weight the models by a quasi-likelihood information criterion, and report intervals that include model uncertainty.'),

('h1', 'Data and Methods'),
('h2', 'Bibliometric Corpus'),
('p', 'Data were retrieved on 26 August 2026 from the OpenAlex REST API [4], aggregated by publication year (endpoint /works, group_by=publication_year) with document type restricted to articles and reviews. The core query D AND E searched titles and abstracts, where D = (drone OR drones OR UAV OR UAVs OR UAS OR "unmanned aerial" OR "unmanned aircraft" OR RPAS OR "remotely piloted aircraft") and E is a disjunction of 24 ecological and environmental terms (ecology, wildlife, biodiversity, habitat, ecosystem, forest, vegetation, "water quality", "air quality", "greenhouse gas", methane, "protected area", wetland, coastal, marine, wildfire and their variants). Three denominators were retrieved with identical filters: E alone (the environmental literature searched in the same way, used as the primary denominator), the OpenAlex field Environmental Science (a classification-based denominator) and all indexed works. Six overlapping sub-domain queries combined D with terms for wildlife surveys, forest health, water quality, air and gas emissions, wildfire, and protected areas or anti-poaching. Because OpenAlex is updated retroactively, the retrieval date is part of the data definition; the exact Boolean strings and a codebook accompany the MATLAB code.'),
('p', 'The fitting window is 2005–2025 (n = 21 complete years); 2026 is incomplete and is excluded. Three limitations must be stated. OpenAlex is broader than Scopus or Web of Science, so absolute counts are higher than those databases would give, while trends and shares are comparable. The query is not perfectly precise. In a manual check of a random sample of 100 records (OpenAlex sample, seed 20260826), coded with AI assistance and independently reviewed by the second author (agreement 78 percent, Cohen\'s kappa 0.64), 60 percent [Wilson 95 percent CI 50, 69] were UAV studies in ecology, environmental or vegetation and agro-ecosystem monitoring, a further 24 percent used a UAV in a non-environmental application (urban survey, security, delivery, platform engineering) and 16 percent were noise ("drone" bees, "UAS" as another acronym, works without a UAV). In an early-period sample (2005–2015, n = 50) the relevant share was 68 percent [54, 79]; the difference is not significant (two-proportion z = 0.95, p = 0.34). A stricter query that excludes agricultural terms grows at 27.9 instead of 29.3 percent per year, so the trend conclusions are robust to this imprecision, whereas absolute counts should be read as roughly 1.7 times the strictly relevant output. The coded samples are included in the repository. Finally, all series jump in 2025 (the environmental denominator by 39 percent), which is partly an indexing artefact; normalisation attenuates it and a sensitivity analysis without 2025 is reported.'),
('h2', 'Descriptive Analysis'),
('p', 'For the counts {i:y{sub:t}} and the share {i:s{sub:t}} = 1000 {i:y{sub:t}}/{i:N{sub:t}} (articles per 1,000 environmental articles) we report the compound annual growth rate, the Mann–Kendall trend test with tie correction and Sen\'s slope with its 90 percent confidence interval [14], [15], and a one-breakpoint segmented log-linear regression found by grid search and tested against a single slope with a Chow-type F test (approximate, because the break is estimated).'),
('h2', 'Growth Models'),
('p', 'Four models of the expected annual output {i:μ}({i:t}) were fitted, with {i:τ} = {i:t} − 2005:'),
('eq', '{i:μ}({i:t}) = {i:a} exp({i:b τ})', 1),
('eq', '{i:μ}({i:t}) = {i:K} / [1 + exp(−{i:r}({i:τ} − {i:t{sub:m}}))]', 2),
('eq', '{i:μ}({i:t}) = {i:K} exp[−exp(−{i:r}({i:τ} − {i:t{sub:m}}))]', 3),
('eq', '{i:μ}({i:t}) = {i:m} [{i:F}({i:τ}+1) − {i:F}({i:τ})]', 4),
('p', 'where (1) is exponential growth without saturation, (2) the logistic and (3) the Gompertz curve with capacity {i:K}, rate {i:r} and inflection year {i:t{sub:m}}, and (4) the Bass diffusion model [10] with market potential {i:m}, coefficient of innovation {i:p} and coefficient of imitation {i:q}, where {i:F}({i:x}) = [1 − e{sup:−({i:p}+{i:q}){i:x}}] / [1 + ({i:q}/{i:p}) e{sup:−({i:p}+{i:q}){i:x}}] is the cumulative adoption fraction. For the share, the same curves describe the rate {i:g}({i:t}) with the denominator as an offset, {i:μ{sub:t}} = {i:N{sub:t}} {i:g}({i:t}), so that share forecasts do not require a forecast of the denominator; the Bass model is omitted for the share because it describes adoptions per period, not a level.'),
('h2', 'Estimation, Model Selection and Uncertainty'),
('p', 'Parameters were estimated by minimising the Poisson deviance'),
('eq', '{i:D} = 2 Σ{sub:{i:t}} [{i:y{sub:t}} ln({i:y{sub:t}}/{i:μ{sub:t}}) − ({i:y{sub:t}} − {i:μ{sub:t}})]', 5),
('p', 'with the Nelder–Mead simplex (MATLAB fminsearch) from multiple starting points and with positive parameters log-transformed. The deviance is the natural least-squares analogue for counts: it gives comparable weight to the small early years and the large late years, and it yields a proper log-likelihood for information criteria. The counts are strongly overdispersed (Pearson dispersion ĉ = 19.8 for the counts, 13.1 for the share), so models were compared with the small-sample quasi-likelihood criterion'),
('eq', 'QAIC{sub:c} = −2 ln {i:L} / ĉ + 2{i:k} + 2{i:k}({i:k}+1)/({i:n}−{i:k}−1)', 6),
('p', 'and combined with Akaike weights [13]. Out-of-sample accuracy was assessed by rolling-origin backtesting: each model was refitted on data up to 2018, 2020 and 2022 and evaluated on the remaining years by the mean absolute percentage error (MAPE) [16]. Forecast uncertainty was obtained by a parametric negative-binomial bootstrap: for each model, 1,000 replicate series were drawn as a gamma–Poisson mixture around the fitted values with the moment-estimated dispersion, every model was refitted on every replicate, the QAIC{sub:c} weights were recomputed and the weighted forecast recorded, giving 90 percent intervals that include both parameter and model uncertainty. Forecasts are reported for 2028, 2030, 2032 and 2035, i.e. 3, 5, 7 and 10 years after the last fitted year. The pipeline (ten MATLAB functions, no toolbox required, also executable in GNU Octave) was independently replicated in Python; parameter estimates and deviances agree to all reported digits.'),

('h1', 'Results'),
('h2', 'Current State'),
('p', 'Annual output rose from 28 articles in 2005 to 4,747 in 2025, a compound annual growth rate of 29.3 percent over the whole period and 30.6 percent over the last ten years; 20,344 articles were published in 2005–2025. The Mann–Kendall test is unambiguous ({i:S} = 209, {i:Z} = 6.28, {i:p} = 3 × 10{sup:−10}), with a Sen slope of 147 articles per year [90 percent CI 105, 194]. The segmented regression locates a break in 2010: growth accelerated from 17 percent to 34 percent per year ({i:F} = 5.5, {i:p} ≈ 0.014, approximate), coinciding with the arrival of low-cost multirotor platforms and MEMS sensors rather than with regulation. Normalised by the environmental literature, the share rose from 0.34 to 11.27 articles per 1,000 (Sen slope 0.60 per 1,000 per year [0.49, 0.76]); within the UAV literature as a whole, the ecological and environmental fraction rose from 2.9 to 18.5 percent.'),
('p', 'Output is concentrated: China (4,410 articles with at least one Chinese author), the United States (3,470), the United Kingdom (1,015), Germany (855) and India (813) lead 182 contributing countries; Croatia contributed 62 articles, all since 2016. The leading venues are Remote Sensing (1,709), Drones (494), the ISPRS Archives (423), Sensors (355) and Forests (307); 72 percent of the corpus is open access and 910 articles have more than 99 citations. Fig. 1 shows the sub-domains. Over 2015–2025 the most mature application, wildlife counting, grew slowest (100 to 547 articles, 18.5 percent per year), whereas forest health grew fastest (114 to 2,079, 33.7 percent), followed by protected areas and anti-poaching (29.6 percent), wildfire (28.3 percent), air and gas emissions (26.8 percent) and water quality (25.8 percent).'),
('fig', 'fig3', 'Annual number of OpenAlex articles combining UAV terms with six environmental sub-domains, 2005–2025 (logarithmic scale; the sub-domain queries overlap).'),
('h2', 'Growth Models for Annual Output'),
('p', 'Table I compares the four models fitted to the annual counts. No model is decisively better: the QAIC{sub:c} weights range from 0.08 (exponential) to 0.41 (Gompertz), and the saturating models disagree about the ceiling. The logistic model places the inflection point in 2025–2026 with a capacity of about 9,700 articles per year, the Bass model peaks in 2029 and then declines, and the Gompertz fit degenerates towards an exponential shape (capacity of millions, inflection in 2086). Backtesting confirms that the data cannot yet separate these shapes: averaged over the three origins, MAPE is 39 to 45 percent for all models; from the 2022 origin the logistic model is best (15 percent), the exponential worst (35 percent).'),
('table', 'Growth Models Fitted to Annual Article Counts, 2005–2025',
    [950, 250, 800, 700, 640, 1396],
    ['Model', '{i:k}', 'Deviance', 'QAIC{sub:c}', 'Weight', 'Parameters'],
    [['Exponential', '2', '469.5', '36.5', '0.083', '{i:a} = 27.5, {i:b} = 0.256 (29.2 %/yr)'],
     ['Logistic', '3', '364.9', '33.9', '0.296', '{i:K} = 9,739, {i:r} = 0.302, {i:t{sub:m}} = 2025.9'],
     ['Gompertz', '3', '352.2', '33.3', '0.408', '{i:K} = 3.7 × 10{sup:6}, {i:r} = 0.031, {i:t{sub:m}} = 2086'],
     ['Bass', '3', '377.9', '34.6', '0.213', '{i:m} = 88,560, {i:p} = 1.8 × 10{sup:−4}, {i:q} = 0.294']],
    ['left', 'center', 'center', 'center', 'center', 'left']),
('p', 'Fig. 2 shows the fits and the forecasts and Table II lists them. The models agree for the three-year horizon (6,100 to 10,000 articles in 2028; model average 8,466 [90 percent interval 5,996, 10,303]) and diverge afterwards: in 2035 the point forecasts range from 3,681 (Bass) to 59,923 (exponential), the model average is 35,872 and the interval spans 10,232 to 62,285. The sensitivity analysis explains the width: without the 2025 observation the logistic capacity falls from 9,739 to about 4,400 and the Bass model predicts a decline, so a single year, which is partly an indexing artefact, doubles the estimated ceiling.'),
('fig', 'fig1', 'Annual OpenAlex articles combining UAV and ecology or environmental terms (dots), four growth models fitted by Poisson deviance (lines) and the QAIC{sub:c}-weighted model average with its 90 percent negative-binomial bootstrap interval (squares, shaded) for 2028–2035.'),
('table', 'Forecast Annual Output: Point Estimates and 90 Percent Bootstrap Intervals of the Model Average',
    [1000, 934, 934, 934, 934],
    ['Model', '2028', '2030', '2032', '2035'],
    [['Exponential', '9,966', '16,639', '27,779', '59,923'],
     ['Logistic', '6,364', '7,551', '8,409', '9,154'],
     ['Gompertz', '7,920', '11,494', '16,309', '26,505'],
     ['Bass', '6,147', '6,474', '5,760', '3,681'],
     ['{b:Model average}', '{b:8,466}', '{b:12,775}', '{b:19,195}', '{b:35,872}'],
     ['90 % interval', '5,996–10,303', '7,198–17,218', '8,241–28,683', '10,232–62,285']],
    ['left', 'center', 'center', 'center', 'center']),
('h2', 'Share of the Environmental Literature'),
('p', 'The picture is different, and much clearer, for the share (Fig. 3). The logistic rate model receives essentially all the weight (0.999; the exponential model is rejected with a QAIC{sub:c} difference of 46) and estimates a plateau of {i:K} = 13.3 articles per 1,000 environmental articles with the inflection in 2019–2020. The share observed in 2025, 11.3 per 1,000, is already 85 percent of that plateau. The model-averaged forecast is 13.1 per 1,000 in 2028 [12.1, 14.7], 13.9 in 2030 [12.6, 16.8] and 15.4 in 2035 [13.1, 21.7], where the upper tail comes from the small residual weight of the Gompertz curve. Backtesting from the 2022 origin gives a MAPE of 10.6 percent for the logistic model against 58 percent for the exponential one. In other words, UAV use in environmental research has stopped growing faster than the field: after 2020 it grows with it.'),
('fig', 'fig2', 'Share of UAV-related articles per 1,000 environmental articles (OpenAlex), fitted exponential, logistic and Gompertz rate models with the environmental literature as offset, and the QAIC{sub:c}-weighted forecast with its 90 percent bootstrap interval.'),

('h1', 'Discussion'),
('h2', 'What the Two Forecasts Mean Together'),
('p', 'Absolute output and share tell one story rather than two. The environmental literature itself grew from 82,000 to 421,000 articles per year between 2005 and 2025 in the same index, so an environmental UAV literature that keeps a constant share of 13 per 1,000 would still grow at the rate of the field, which is what the logistic and Gompertz count models describe. The exponential count model, which implies a further tenfold rise in share by 2035, is contradicted by the share analysis and should be discarded despite its non-negligible weight on the counts alone. Our reading of the evidence is therefore that the UAV has completed its transition from a novel research topic to a standard sensing platform, and that the reliable forecast horizon for the absolute count is about three years; beyond that, the question "which curve" dominates any statistical uncertainty, and reporting a single point forecast for 2035 would be misleading.'),
('h2', 'Implications for the Robotics Community'),
('p', 'If the platform is now standard, future value lies less in "another UAV application" than in the sensing and autonomy requirements of the sub-domains that are still accelerating, and the accuracy evidence in Section II shows what those requirements are. Wildlife counting, where UAVs already outperform humans [5], is the slowest-growing sub-domain. Forest health, the fastest, is limited by the sensitivity of early detection: multispectral imagery finds only a minority of infested trees in the green-attack phase and most of them only when discoloration is already visible [6], which calls for hyperspectral or thermal payloads that stay within the mass and power budget of small multirotors, and for revisit scheduling rather than single surveys. Water quality is limited by sensor design: the commonly used multispectral cameras have no band centred on phycocyanin, the pigment that best indicates cyanobacterial biomass [7]. Gas emission quantification is limited by uncertainty: fluxes from the same source differ by a factor of four between methods [8], so flight patterns that sample the plume cross-section systematically, and on-board estimation of the flux uncertainty, are worth more than another sensor. Finally, the disturbance evidence [9] translates directly into design rules: electric propulsion, small airframes, non-target-oriented approach paths and altitude adapted to taxon and life stage. These are engineering problems, and the growth data indicate that they are where the environmental demand for UAV research will be over the next decade.'),
('h2', 'Operational and Regulatory Context'),
('p', 'Publication growth has outpaced the growth of the operational base. In the United States, new commercial UAV registrations peaked at about 175,000 in 2018 and fell to about 124,000 in 2024, while remote pilot certificates reached 493,000 in 2025 [17]. In Europe, the European Union Aviation Safety Agency reported more than two million registered operators in 2025 [18]; Spain registered 150,332 operators by the end of 2025, a 26 percent annual increase. Croatia had 2,464 registered UAS operators, 9,633 remote pilots and 18 authorisations in the "specific" category in 2024 [19]. Since Regulation (EU) 2019/947 became applicable on 31 December 2020 [20], most environmental monitoring missions fall in the "open" category, but beyond-visual-line-of-sight surveys of large habitats, which are exactly what forest health and emission mapping need, require the "specific" category and a risk assessment. In Croatia, flights in protected areas additionally require the approval of the public institution managing the area [21], and some national parks have prohibited recreational UAV use altogether. The areas where UAV monitoring would be most useful are thus the areas with the most restricted access, a paradox that autonomy (reliable geofencing, conservative failsafes, low-noise operation) can help to resolve.'),
('h2', 'Limitations'),
('p', 'Four limitations bound the conclusions. First, the corpus depends on one index and one query whose precision is 60 percent; OpenAlex covers more regional venues than Scopus, and a replication of the same Boolean query in Scopus is planned. Second, the 2025 observation is partly an indexing artefact and carries disproportionate weight in the saturating models, as the sensitivity analysis shows. Third, the sub-domain queries overlap and are not nested in the core query, so they describe relative growth, not partition of the total. Fourth, model uncertainty is represented by four parametric shapes only; a change in indexing policy or a regulatory shock would not be captured by any of them, and the breakpoint test is approximate. The registry figures are heterogeneous snapshots and are used for context only.'),

('h1', 'Conclusion'),
('p', 'A reproducible bibliometric series shows that research on UAVs in ecology and environmental protection grew by 29 percent per year between 2005 and 2025, with a structural acceleration in 2010, and that its share of the environmental literature is saturating at about 13 articles per 1,000. Four growth models fitted and averaged in a toolbox-free MATLAB pipeline agree on a three-year forecast of roughly 8,500 articles in 2028 but diverge widely by 2035; the share forecast is robust. Growth is migrating from mature applications to sub-domains with open sensing, uncertainty and autonomy problems, which is where the robotics community can make the largest contribution. The data, the query definitions and the code are provided with this paper as an openly archived repository [22] so that the analysis can be repeated at any future retrieval date.'),
]

ACK = ('The authors used generative AI tools (Anthropic Claude) for statistical code generation, data retrieval scripting and language editing. '
       'All analyses were executed and verified by the authors, who take full responsibility for the content.')

REFERENCES = [
 'K. Anderson and K. J. Gaston, "Lightweight unmanned aerial vehicles will revolutionize spatial ecology," {i:Frontiers in Ecology and the Environment}, vol. 11, no. 3, pp. 138–146, 2013.',
 'L. P. Koh and S. A. Wich, "Dawn of drone ecology: low-cost autonomous aerial vehicles for conservation," {i:Tropical Conservation Science}, vol. 5, no. 2, pp. 121–132, 2012.',
 'S. Manfreda {i:et al.}, "On the use of unmanned aerial systems for environmental monitoring," {i:Remote Sensing}, vol. 10, no. 4, art. 641, 2018.',
 'J. Priem, H. Piwowar, and R. Orr, "OpenAlex: A fully-open index of scholarly works, authors, venues, institutions, and concepts," arXiv:2205.01833, 2022.',
 'J. C. Hodgson {i:et al.}, "Drones count wildlife more accurately and precisely than humans," {i:Methods in Ecology and Evolution}, vol. 9, no. 5, pp. 1160–1167, 2018.',
 'R. Näsi {i:et al.}, "Using UAV-based photogrammetry and hyperspectral imaging for mapping bark beetle damage at tree-level," {i:Remote Sensing}, vol. 7, no. 11, pp. 15467–15493, 2015.',
 'D. Olivetti {i:et al.}, "Comparing unmanned aerial multispectral and hyperspectral imagery for harmful algal bloom monitoring in artificial ponds used for fish farming," {i:Drones}, vol. 7, no. 7, art. 410, 2023.',
 'J. T. Shaw, A. Shah, H. Yong, and G. Allen, "Methods for quantifying methane emissions using unmanned aerial vehicles: a review," {i:Philosophical Transactions of the Royal Society A}, vol. 379, art. 20200450, 2021.',
 'M. Mulero-Pázmány, S. Jenni-Eiermann, N. Strebel, T. Sattler, J. J. Negro, and Z. Tablado, "Unmanned aircraft systems as a new source of disturbance for wildlife: A systematic review," {i:PLoS ONE}, vol. 12, no. 6, art. e0178448, 2017.',
 'F. M. Bass, "A new product growth for model consumer durables," {i:Management Science}, vol. 15, no. 5, pp. 215–227, 1969.',
 'N. Meade and T. Islam, "Modelling and forecasting the diffusion of innovation – A 25-year review," {i:International Journal of Forecasting}, vol. 22, no. 3, pp. 519–545, 2006.',
 'L. Bornmann and R. Mutz, "Growth rates of modern science: A bibliometric analysis based on the number of publications and cited references," {i:Journal of the Association for Information Science and Technology}, vol. 66, no. 11, pp. 2215–2222, 2015.',
 'K. P. Burnham and D. R. Anderson, {i:Model Selection and Multimodel Inference: A Practical Information-Theoretic Approach}, 2nd ed. New York, NY, USA: Springer, 2002.',
 'H. B. Mann, "Nonparametric tests against trend," {i:Econometrica}, vol. 13, no. 3, pp. 245–259, 1945.',
 'P. K. Sen, "Estimates of the regression coefficient based on Kendall\'s tau," {i:Journal of the American Statistical Association}, vol. 63, no. 324, pp. 1379–1389, 1968.',
 'R. J. Hyndman and A. B. Koehler, "Another look at measures of forecast accuracy," {i:International Journal of Forecasting}, vol. 22, no. 4, pp. 679–688, 2006.',
 'Federal Aviation Administration, "FAA Aerospace Forecast Fiscal Years 2026–2046: Emerging Aviation Entrants – Unmanned Aircraft Systems and Advanced Air Mobility," Washington, DC, USA, 2026. [Online]. Available: https://www.faa.gov/data_research/aviation/aerospace_forecasts',
 'European Union Aviation Safety Agency, "EASA launches Drone Economy Dashboard," press release, Cologne, Germany, May 2025. [Online]. Available: https://www.easa.europa.eu/en/newsroom-and-events/press-releases',
 'Hrvatska agencija za civilno zrakoplovstvo (Croatian Civil Aviation Agency), "Godišnje izvješće o radu za 2024. godinu" (Annual Report 2024), Zagreb, Croatia, 2025.',
 'Commission Implementing Regulation (EU) 2019/947 of 24 May 2019 on the rules and procedures for the operation of unmanned aircraft, {i:Official Journal of the European Union}, L 152, pp. 45–71, 2019.',
 'Croatian Civil Aviation Agency, "Letenje dronom" (Flying a drone), guidance page. Accessed: Aug. 26, 2026. [Online]. Available: https://www.ccaa.hr/letenje-dronom-98073',
 'V. Uroš and M. Jelić, "drone-ecology-forecast: bibliometric data and MATLAB growth-model pipeline for UAV research in ecology and environmental monitoring (v1.0)," Zenodo, 2026, doi: 10.5281/zenodo.22119199.',
]
